### ISSUE TITLE
Version-15 Release

### ISSUE THREAD

**Issue by agritheory** [agritheory/electronic_payments#30]

**Comment by HKuz** [comment]
`version-15` branch and initial release is up. It includes a test suite and working CI 

One nice thing is that frappe version-15 updated how it loads template pages so we no longer have to manipulate the installed app ordering for it to find our `order.py` and `order.html` changes - we just need to make sure electronic_payments comes after erpnext and webshop.

The tests do not make calls or mock calls to the API - they're written to assume a successful response, and use randomly-generated ints as API keys (in Settings) and for the "token" values that represent a saved party or payment method in the API. They test the accounting for different scenarios both receiving and sending payments.
